config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'shift/index'
  get 'shift/create'
  root to: "shift#index"
  resources :user
  resources :shift, only: [:index, :new, :create, :edit]
  resources :days, only: [:index, :new, :create, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :ok
  belongs_to :user
end

app/models/form/base.rb
class Form::Base
  include ActiveModel::Model
  include ActiveModel::Callbacks
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks
  include ActiveModel::Attributes
end

app/models/form/day_collection.rb
class Form::DayCollection < Form::Base
  FORM_COUNT = 1 #ここで、作成したい登録フォームの数を指定
  attr_accessor :days 
  attribute :user_id
  def initialize(attributes = {})
    super attributes
    self.days = FORM_COUNT.times.map { Day.new() } unless self.days.present?
  end

  def days_attributes=(attributes)
    self.days = attributes.map { |_, v| Day.new(v) }
  end

  def save
    Day.transaction do
      self.days.map do |day|
        day.save
      end
    end
  end

end

app/models/ok.rb
class Ok < ActiveHash::Base
  self.data = [
    { id: 1, name: '-' },
    { id: 2, name: '○' },
    { id: 3, name: '×' }
  ]

  include ActiveHash::Associations
  has_many :days
  end

app/models/shift.rb
class Shift < ApplicationRecord
  has_many :user_shifts
  has_many :users, through: :user_shifts
  has_many :days
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name
    validates :position_id
  end

  has_many :days
  has_many :user_shifts
  has_many :shifts, through: :user_shifts
end

app/models/user_shift.rb
class UserShift < ApplicationRecord
  belongs_to :shift
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index
  end
  
  def new
    @form = Form::DayCollection.new
    @user = current_user.id
  end

  def create
    @user = current_user.id
    @form = Form::DayCollection.new(day_collection_params)
    if @form.save
      redirect_to root_path
    else
      flash.now[:alert] = "登録に失敗しました"
      render :new
    end
  end

  private

  def day_collection_params
    params.require(:form_day_collection).permit(days_attributes: [:ok_id, :shift_date, :user_id])
  end
end

app/controllers/shift_controller.rb
class ShiftController < ApplicationController
  def index
  end

  def new
    @shift = Shift.new
  end

  def create
    @user_days = Day.where(shift_date: params[:date_save], ok_id: 2)
    @num = []
    @user_days.each do |name|
      @num << User.find(name.user_id)
    end
  end

  def edit
  end

  private
  def shift_params
    params.require(:shift).merge(user_id: params[:user_id], ok_id: params[:ok_id], shift_date: params[:shift_date])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/shift_helper.rb
module ShiftHelper
end

app/views/days/new.html.erb
<%= form_with(model: @form, url: days_path, local: true) do |form| %>
  <%= month_calendar do |date| %>
    <%= form.fields_for :days do |f| %>
      <%= date %>
      <%= f.collection_select(:ok_id, Ok.all, :id, :name, {}, {class:"ok-select"}) %>
      <%= f.hidden_field :shift_date, value: date %>
      <%= f.hidden_field :user_id, value: @user %>
    <% end %>
  <% end %>
  <%= form.submit "SEND" %>
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShiftApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='nav'>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.name, root_path, class: "user-name" %></li> 
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shift/create.html.erb
<div class="shift_main">
  <%= params[:date_save] %>
  <div class="shift_set">
    <table class="shift_table">
      <tbody class="shift_table_body">
        <tr class="shift_line">
          <td id="shift_num1" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
          <td id="shift_num2" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
        </tr>
        <tr class="shift_line">
          <td id="shift_num3" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
          <td id="shift_num4" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
        </tr>
        <tr class="shift_line">
          <td id="shift_num5" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
          <td id="shift_num6" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
        </tr>
        <tr class="shift_line">
          <td id="shift_num7" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
          <td id="shift_num8" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
        </tr>
        <tr class="shift_line">
          <td id="shift_num9" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
          <td id="shift_num10" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
        </tr>
        <tr class="shift_line">
          <td id="shift_num11" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
          <td id="shift_num12" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
        </tr>
        <tr class="shift_line">
          <td id="shift_num13" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
          <td id="shift_num14" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
        </tr>
        <tr class="shift_line">
          <td id="shift_num15" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
          <td id="shift_num16" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
        </tr>
        <tr class="shift_line">
          <td id="shift_num17" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
          <td id="shift_num18" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
          </tr>
        <tr class="shift_line">
          <td id="shift_num19"  ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
          <td id="shift_num20" ondragover="onDragOver(event);" ondrop="onDrop(event);"></td>
        </tr>
      </tbody>
    </table>
    <table>
      <tbody>
        <% @num.each do |day| %>
          <tr>
            <td class="employee">
              <div id="human1" class="employee_name" draggable="true" ondragstart="onDragStart(event);">
                <%= day.name %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<script type="text/javascript">
function onDragStart(event)
{
    const nodes = Array.from(document.querySelectorAll(".employee_name"));
    const index = nodes.findIndex(v=>v===event.target);
    event.dataTransfer.setData('text/plain', index);
}


function onDragOver(event) {
  event.preventDefault();
}

function onDrop(event)
{
    event.preventDefault();
    const index = event.dataTransfer.getData('text');
    const draggableElement = document.querySelectorAll(".employee_name")[index];
    const dropzone = event.currentTarget;
    dropzone.appendChild(draggableElement);
}
</script>

app/views/shift/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='contents'>
    <div class='create-shift'>
      <%= link_to(new_shift_path) do %>
        <span class='purchase-btn-text'>シフトを作成する</span>
      <% end %>
    </div>
    <div class='submit-shift'>
      <%= link_to(new_day_path) do %>
        <span class='purchase-btn-text'>シフトを提出する</span>
      <% end %>
    </div>
    <div class='check-shift'>
      <%= link_to(root_path, class: 'purchase-btn') do %>
        <span class='purchase-btn-text'>シフトを確認する</span>
      <% end %>
    </div>
  </div>
</div>

app/views/shift/new.html.erb
<%= month_calendar do |date| %>
  <%= link_to shift_create_path(date_save: date) do %>
    <span class='purchase-btn-text'>
    <%= date %>作成
    </span>
  <% end %>
<% end %>